{
  "version": "7.0.0",
  "dialect": "postgresql",
  "steps": [
    {
      "stepType": "CreateTable",
      "createTable": {
        "isGenerated": false,
        "tableName": "denuncias"
      }
    },
    {
      "stepType": "CreateTable",
      "createTable": {
        "isGenerated": false,
        "tableName": "denuncia_votos"
      }
    },
    {
      "stepType": "CreateTable",
      "createTable": {
        "isGenerated": false,
        "tableName": "denuncia_comentarios"
      }
    }
  ]
}
